//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCajaBanco
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_recibos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cxc_recibos()
        {
            this.cxc_medio_pago = new HashSet<cxc_medio_pago>();
        }
    
        public string auto { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha { get; set; }
        public string auto_usuario { get; set; }
        public decimal importe { get; set; }
        public string usuario { get; set; }
        public decimal monto_recibido { get; set; }
        public string cobrador { get; set; }
        public string auto_cliente { get; set; }
        public string cliente { get; set; }
        public string ci_rif { get; set; }
        public string codigo { get; set; }
        public string estatus_anulado { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string auto_cobrador { get; set; }
        public decimal anticipos { get; set; }
        public decimal cambio { get; set; }
        public string nota { get; set; }
        public string codigo_cobrador { get; set; }
        public string auto_cxc { get; set; }
        public decimal retenciones { get; set; }
        public decimal descuentos { get; set; }
        public string hora { get; set; }
        public string cierre { get; set; }
        public string cierre_ftp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cxc_medio_pago> cxc_medio_pago { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
