//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCajaBanco
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cajaBancoEntities : DbContext
    {
        public cajaBancoEntities()
            : base("name=cajaBancoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cxc_recibos> cxc_recibos { get; set; }
        public virtual DbSet<empresa_depositos> empresa_depositos { get; set; }
        public virtual DbSet<empresa_grupo> empresa_grupo { get; set; }
        public virtual DbSet<empresa_sucursal> empresa_sucursal { get; set; }
        public virtual DbSet<sistema> sistema { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<cxc_medio_pago> cxc_medio_pago { get; set; }
        public virtual DbSet<pos_arqueo> pos_arqueo { get; set; }
    }
}
