//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCajaBanco
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistema
    {
        public string estatus_bienvenido { get; set; }
        public string bienvenido { get; set; }
        public string deposito_principal { get; set; }
        public string codigo_empresa { get; set; }
        public int id { get; set; }
        public string prefijo { get; set; }
    }
}
